### PR TITLE
Refactors to a component-based methodology

### PR DESCRIPTION
**Pull request by jacwright**

### CODE REVIEW

**Comment by matthopson** [comment]
Going to take me all day! :stuck_out_tongue:

**Comment by jacwright** [comment]
I haven't updated examples yet. Work in Progress. Do not merge.

**Comment by matthopson** [comment]
Why these lies!?

**Comment by jacwright** [comment]
Closing this pull request out. Meant to PR against the 2.0 branch and it doesn't appear there is a way to switch that without creating a new one.

**Comment by matthopson** [comment]
@jacwright Yeah, this has bit me a few times...

**Pull request closed without merging**
